/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.io.IOException;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InvalidFormatException, IOException {
        System.out.println("Excel Summarize starting...");
        String path = args[0];
    	ExcelReader reader = new ExcelReader(path);
        String content = reader.getFileContent();
        
        AISummarize summarizer = new AISummarize();
        String summary = summarizer.callSummarize(content);
        System.out.println(summary);
    }
}
